Improve error checking
Add quoting throughout shell scripts to protect against errors; improve error checking in scripts that require only a single parameter

Signed-off-by: Scott Lowe <scott.lowe@scottlowe.org>

diff --git a/mdpmmd b/mdpmmd
--- a/mdpmmd
+++ b/mdpmmd
@@ -5,25 +5,16 @@ HELP="Usage: mdpmmd [MARKDOWN FILE]"
 
 # Ensure that only a single parameter was passed
 # Display help text if more than 1 parameter was supplied
-if [ $# -gt 1 ]; then
-    echo "Error: Too many parameters. Please supply only a single file name."
+if [ "$#" -ne 1 ]; then
+    echo "Error: Incorrect number of parameters. Please supply only a single file name."
     echo
     echo $HELP
     echo
-    exit
-fi
-
-# Test to be sure user supplied a parameter; error if not
-if [ $# -eq 0 ]; then
-    echo "Error: No filename supplied."
-    echo
-    echo $HELP
-    echo
-    exit
+    exit 1
 fi
 
 # Check to see if the user supplied "--help"
-if [ $1 = "--help" ]; then
+if [ "$1" = "--help" ]; then
     echo $HELP
     echo
     exit
@@ -39,7 +30,7 @@ fi
 
 # Generate new Markdown preview file
 /opt/bin/multimarkdown --output=/tmp/$TMPFILE \
-    --to=html --full --smart $1
+    --to=html --full --smart "$1"
 
 # Open generated preview file in Firefox
 # Assumes firefox binary is in the path
